### ISSUE TITLE
Project not work under PHP 8.1

### ISSUE THREAD

**Issue by sasha2002** [PHPixie/Project#53]
```
2022/09/06 21:25:29 [error] 29485#29485: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of PHPixie\Config\Storages\Type\File::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/PROJECT/vendor/phpixie/config/src/PHPixie/Config/Storages/Type/File.php:83
Stack trace:
#0 /var/www/PROJECT/vendor/phpixie/debug/src/PHPixie/Debug/Handlers.php(33): PHPixie\Debug\Handlers->handleError()
#1 /var/www/PROJECT/vendor/phpixie/config/src/PHPixie/Config/Storages/Type/File.php(5): PHPixie\Debug\Handlers->PHPixie\Debug\{closure}()
#2 /var/www/PROJECT/vendor/composer/ClassLoader.php(571): include('...')
#3 /var/www/PROJECT/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#4 /var/www/PROJECT/vendor/phpixie/config/src/PHPixie/Config/Storages.php(18): Composer\Autoload\ClassLoader->loadClass()
#5 /var/www" while reading response header from upstream, client: IP, server: PROJECT, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "PROJECT"
```

```
USER # ./console framework:database drop
ErrorException: Optional parameter $path declared before required parameter $value is implicitly treated as a required parameter

6  {
7      public function remove($path = null);
>>     public function set($path = null, $value);
9      public function slice($path = null);
10 }

```

**Comment by Shwethamn8** [comment]
Hi Please let me know if you are able to migrate it to php8.1?   is Phpixie compatible with php8?

**Comment by ftw-soft** [comment]
I'm afraid that this project is not maintaining anymore. The last commit was 6 years ago and I doubt that this gonna change in the future
